#!/usr/bin/env python3
"""Publish one finished step of the rerun session: tables, curated evidence, timeline, ledger, push.

Called by `bench/blog_study.py chain --publish` after a step's server has stopped, so nothing here
runs beside a measurement. It can also be run by hand:

  BLOG_STUDY=five-model-rerun-h100-v1 python bench/session_publish.py diag:v4-0731
  BLOG_STUDY=five-model-rerun-h100-v1 python bench/session_publish.py all --no-push

What it writes under reports/<study>/:
  serving.csv pilot.csv memory.csv decode_intervals.csv natural.csv   tables from results/<study>/
  data/<key>/      curated raw runs of the step's model (bench/curate.py; traces stay on the node)
  study/           plan, input hashes, node inventory, chain log, shutdown log, timeline
  timeline.md      when each step of each model started and finished (UTC)
  results.md       the readable tables, generated by tools/build_rerun_results.py from the CSVs
  provenance.json  SHA-256 of every file above; tools/audit_references.py verifies it
Credentials come from the Git credential helper of the node, never from this repository.
"""
import datetime, fcntl, hashlib, json, os, subprocess, sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import blog_report as br

ROOT, STUDY, SDIR, RDIR = br.ROOT, br.STUDY, br.SDIR, br.RDIR
STAGE = {"diag": "Diagnostics", "routing": "Expert-routing statistics", "hbm": "HBM counters", "timing": "Timing block"}


def utc():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def git(*args, check=True):
    r = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True)
    if check and r.returncode:
        raise RuntimeError(f"git {' '.join(args)}: {r.stdout}{r.stderr}")
    return r.stdout.strip()


def timeline():
    """reports/<study>/timeline.md from the chain's timeline.jsonl."""
    path = SDIR / "_logs" / "timeline.jsonl"
    events = [json.loads(l) for l in open(path)] if path.exists() else []
    plan = br.load(SDIR / "plan.json") or {}
    steps = {}
    for e in events:
        s = steps.setdefault(e["step"], dict(model=e["model"], start=None, end=None, outcome=None, attempts=0))
        if e["event"] == "start":
            s["start"] = s["start"] or e["utc"]
            s["attempts"] = max(s["attempts"], e.get("attempt", 1))
        else:
            s["end"], s["outcome"] = e["utc"], e["outcome"]
    out = [f"# Session timeline: `{STUDY}`\n",
           "Generated by `bench/session_publish.py` from the chain's own log. All times are UTC. A step is one "
           "owned server launch; its end time is taken after the server has stopped. **Measurements complete** is "
           "the end of a model's third timing block.\n",
           "## When each model finished\n",
           "| Model | Diagnostics | Routing statistics | HBM counters | Timing 1 | Timing 2 | Timing 3 | Measurements complete |",
           "| --- | --- | --- | --- | --- | --- | --- | --- |"]

    def cell(st):
        s = steps.get(st)
        if not s:
            return "pending"
        if not s["end"]:
            return f"running since {s['start'][11:16]}"
        return s["end"][11:16] if s["outcome"] == "done" else f"{s['outcome']} {s['end'][11:16]}"

    for mk in br.MODELS:
        last = steps.get(f"timing:{mk}:3")
        done = f"**{last['end'].replace('T', ' ').replace('Z', ' UTC')}**" if last and last["outcome"] == "done" else "pending"
        out.append(f"| {br.NAME[mk]} | {cell(f'diag:{mk}')} | {cell(f'routing:{mk}')} | {cell(f'hbm:{mk}')} | "
                   + " | ".join(cell(f"timing:{mk}:{b}") for b in (1, 2, 3)) + f" | {done} |")
    out += ["\nTimes are `HH:MM` on the day the step ended; the table below has the full timestamps. `pending` means "
            "the step has not run. Gated stages that stopped at their gate are reported in the study's results, not "
            "as a completed step here.\n",
            "## Every step\n", "| Step | Model | Started | Finished | Minutes | Outcome | Launch attempts |",
            "| --- | --- | --- | --- | ---: | --- | ---: |"]
    for st, s in steps.items():
        mins = ""
        if s["start"] and s["end"]:
            f = lambda x: datetime.datetime.strptime(x, "%Y-%m-%dT%H:%M:%SZ")
            mins = f"{(f(s['end']) - f(s['start'])).total_seconds() / 60:.1f}"
        out.append(f"| `{st}` | {br.NAME.get(s['model'], s['model'])} | {s['start'] or ''} | {s['end'] or ''} | {mins} | "
                   f"{s['outcome'] or 'running'} | {s['attempts']} |")
    if plan:
        out.append(f"\nBuild: vLLM `{plan.get('runtime_commit')}` (`{plan['runtime']['vllm']}`). Plan frozen "
                   f"{plan.get('frozen_utc')}.")
    (RDIR / "timeline.md").write_text("\n".join(out) + "\n")
    return steps


def ledger():
    files = []
    for p in sorted(RDIR.rglob("*")):
        if p.is_file() and p != RDIR / "provenance.json":
            raw = p.read_bytes()
            files.append(dict(path=p.relative_to(ROOT).as_posix(), sha256=hashlib.sha256(raw).hexdigest(), bytes=len(raw)))
    doc = dict(study=STUDY, policy="Every file of this study folder. Raw runs are curated by bench/curate.py and "
               "study records by bench/blog_report.py publish; each has its own CURATION.json with the source hash "
               "on the node. Tables are generated from results/ on the node. Full profiler traces, public input "
               "texts, weights and caches are not in Git.", generated_utc=utc(), files=files)
    (RDIR / "provenance.json").write_text(json.dumps(doc, indent=1) + "\n")
    return len(files)


def main():
    step = sys.argv[1]
    push = "--no-push" not in sys.argv
    kind, mk = (step.split(":") + [None])[:2]
    RDIR.mkdir(parents=True, exist_ok=True)
    with open(SDIR / "_logs" / "publish.lock", "w") as lock:
        fcntl.flock(lock, fcntl.LOCK_EX)  # one publisher at a time (a background analysis may also publish)
        tables = [br.serving, br.session_pilot, br.session_memory, br.session_intervals, br.session_natural,
                  br.session_routing, br.session_support, br.session_windows]
        # Trace classification reads the new traces (cached per capture afterwards). A classifier change is
        # applied at the next step boundary by touching _logs/recompute_components: the server is stopped
        # then, so the minute of parsing never runs beside a timing run.
        flag = SDIR / "_logs" / "recompute_components"
        if kind in ("diag", "all", "components") or flag.exists():
            tables.append(br.session_components)
            flag.unlink(missing_ok=True)
        for table in tables:
            try:
                table()
            except Exception as e:
                print(f"table {table.__name__} failed: {e!r}")
        (RDIR / "serving_tables.md").unlink(missing_ok=True)  # superseded by the generated results page
        br.publish(only=br.MODELS if kind == "all" else [mk])
        steps = timeline()
        sys.path.insert(0, str(ROOT / "tools"))
        import build_rerun_results  # the generated results page; the audit checks that it is not stale
        for rel, body in build_rerun_results.generate().items():
            (ROOT / rel).write_text(body, encoding="utf-8", newline="\n")
        n = ledger()
        git("add", "-A", "--", f"reports/{STUDY}")
        if not git("status", "--porcelain", "--", f"reports/{STUDY}"):
            print(f"published {step}: nothing new"); return
        s = steps.get(step, {})
        title = (f"{STAGE.get(kind, kind)}{' ' + step.split(':')[2] if kind == 'timing' else ''}: "
                 f"{br.NAME.get(mk, mk)} {s.get('outcome') or 'updated'} at {s.get('end') or utc()}")
        done = [br.NAME[m] for m in br.MODELS if steps.get(f"timing:{m}:3", {}).get("outcome") == "done"]
        body = (f"Rerun session {STUDY}, step {step}. Evidence under reports/{STUDY}/data/{mk}/, "
                f"times in reports/{STUDY}/timeline.md.\n"
                + (f"Measurements complete for: {', '.join(done)}.\n" if done else "")
                + "\nCo-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>")
        git("commit", "-q", "-m", f"Rerun session: {title}", "-m", body, "--", f"reports/{STUDY}")
        if push:
            r = subprocess.run(["git", "push", "-q", "origin", "HEAD:main"], cwd=ROOT, capture_output=True, text=True)
            if r.returncode:  # someone else pushed meanwhile: replay this commit on top, then push again
                subprocess.run(["git", "pull", "-q", "--rebase", "--autostash", "origin", "main"], cwd=ROOT,
                               capture_output=True, text=True)
                r = subprocess.run(["git", "push", "-q", "origin", "HEAD:main"], cwd=ROOT, capture_output=True, text=True)
            print(f"published {step}: {n} files, commit {git('rev-parse', '--short', 'HEAD')}, "
                  f"push {'ok' if r.returncode == 0 else 'FAILED ' + r.stderr.strip()[-200:]}")
        else:
            print(f"published {step}: {n} files, commit {git('rev-parse', '--short', 'HEAD')}, not pushed")


if __name__ == "__main__":
    main()
